---
stages:
  - build
  - release

variables:
  GIT_STRATEGY: clone

build:
  stage: build
  image: python:3.6-alpine
  before_script:
    - apk update -q --no-cache
    - apk add -q --no-cache gcc bash make py-setuptools musl-dev libxml2 libxml2-dev
    - python3 -m pip install -U pip
    - python3 -m pip install -r requirements.txt
  script:
    - make build
  only:
    - master

upload-test:
  stage: release
  image: python:3.6-alpine
  before_script:
    - apk update -q --no-cache
    - apk add -q --no-cache gcc bash make py-setuptools musl-dev libxml2 libxml2-dev
    - python3 -m pip install -U pip
    - python3 -m pip install -r requirements.txt
  script:
    - make upload-test
  only:
    - master

upload-pypi:
  stage: release
  image: python:3.6-alpine
  before_script:
    - apk update -q --no-cache
    - apk add -q --no-cache gcc bash make py-setuptools musl-dev libxml2 libxml2-dev
    - python3 -m pip install -U pip
    - python3 -m pip install -r requirements.txt
  script:
    - make upload-pypi
  only:
    - master
