---
stages:
  - release

variables:
  GIT_STRATEGY: clone

.upload-test:
  stage: release
  image: python:3.6-alpine
  before_script:
    - apk update -q --no-cache
    - apk add -q --no-cache gcc bash make py-setuptools musl-dev libxml2-dev libxslt-dev libffi-dev
  script:
    - make upload-test
  only:
    - master

upload-pypi:
  stage: release
  image: python:3.6-alpine
  before_script:
    - apk update -q --no-cache
    - apk add -q --no-cache gcc bash make py-setuptools musl-dev libxml2-dev libxslt-dev libffi-dev
  script:
    - make upload-pypi
  only:
    - master
