---
stages:
  - build
  - release

variables:
  GIT_STRATEGY: clone

build:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get -yqq upgrade
    - apt-get install -yqq gcc build-essential bash make git jq curl python3 python3-dev python3-pip python3-setuptools
    - pip3 install -U pip setuptools
    - pip3 install -r requirements.txt
  script:
    - make build
  only:
    - master

upload-test:
  stage: release
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get -yqq upgrade
    - apt-get install -yqq gcc build-essential bash make git jq curl python3 python3-dev python3-pip python3-setuptools
    - pip3 install -U pip setuptools
    - pip3 install -r requirements.txt
  script:
    - make upload-test
  only:
    - master

upload-pypi:
  stage: release
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get -yqq upgrade
    - apt-get install -yqq gcc build-essential bash make git jq curl python3 python3-dev python3-pip python3-setuptools
    - pip3 install -U pip setuptools
    - pip3 install -r requirements.txt
  script:
    - make upload-test
  only:
    - master
